name: Coverage Check

on: [push]

env:
    COVERAGE_SENSITIVITY_PERCENT: 1

jobs:
  upload-coverage:
    name: Upload Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Run coverage
        shell: bash
        run: forge coverage --report summary --report lcov --match-contract Unit

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Filter directories
        run: lcov --remove lcov.info 'test/*' 'script/*' --output-file lcovNew.info --rc lcov_branch_coverage=1 --rc derive_function_end_line=0 --ignore-errors unused

      - name: Capture coverage output
        id: new-coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: lcovNew.info

      - name: Retrieve previous coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage.info
        continue-on-error: true

      - name: Check if a previous coverage exists
        run: |
          if [ ! -f coverage.info ]; then
            echo "Artifact not found. Initializing at 0"
            echo "0" >> coverage.info
          fi

      - name: Compare previous coverage
        run: |
          old=$(cat coverage.info)
          new=$(( ${{ steps.new-coverage.outputs.total-coverage }} + ${{ env.COVERAGE_SENSITIVITY_PERCENT }} ))
          if [ "$new" -lt "$old" ]; then
            echo "Coverage decreased from $old to $new"
            exit 1
          fi
          mv lcovNew.info coverage.info

      - name: Upload the new coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage.info
          path: ./coverage.info
